# Stage 1 - Билд приложения
FROM node:14 as build

WORKDIR /app

COPY nginx.conf .

RUN git clone https://github.com/codebucks27/React-Weather-app.git

WORKDIR /app/React-Weather-app

RUN npm install

RUN npm run build

# Stage 2 - Запуск приложения
FROM nginx:alpine

COPY --from=build /app/React-Weather-app/build /usr/share/nginx/html

COPY --from=build /app/nginx.conf /etc/nginx/conf.d/default.conf

EXPOSE 80

CMD ["nginx", "-g", "daemon off;"]
