# для работы с приложением требуется запустить контейнер в фоновом режиме, после чего запустить терминал внутри контейнера:
# docker run -d --name <container_name> <image_name>; docker exec -it <container_name> bash
FROM python:3.13

RUN git clone https://github.com/francoischalifour/todo-cli

WORKDIR /todo-cli

RUN pip install .

WORKDIR /app

CMD ["tail", "-f", "/dev/null"]
