FROM python:3.9

WORKDIR /app

COPY ./requirements.txt /app/requirements.txt

RUN pip install --no-cache-dir --upgrade -r /app/requirements.txt

COPY ./web_app /app/web_app

EXPOSE 8080

CMD ["fastapi", "run", "web_app/main.py", "--port", "8080"]